spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fyp_db
    username: postgres
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: fyp-backend

server:
  port: 8080
